import type { NextPage } from 'next';
import Head from 'next/head';
import { Header } from 'components/Header';

const Home: NextPage = () => {
	return (
		<div className="sm:bg-caribbean-green md:bg-orange-yellow lg: bg-ultra-red  h-40">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1 className="shadow">Screen size</h1>
				<Header />
			</main>
		</div>
	);
};

export default Home;
