import type { NextPage } from 'next';
import Head from 'next/head';
import { Header } from 'components/Header';
import supabase from 'utils/supabase';

const Home: NextPage = () => {
	const testClick = async () => {
		const data = await supabase.from('auth').select();
		console.log('🚀 ~ file: index.tsx ~ line 9 ~ testClick ~ data', data);
	};

	return (
		<div className="sm:bg-caribbean-green md:bg-orange-yellow lg: bg-ultra-red  h-40">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<button onClick={testClick} className="absolute bottom-0">
				Test
			</button>
		</div>
	);
};

export default Home;
